const portfolioImages = [
    { id: 1, src: "./img/ph/1.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 2, src: "./img/ph/2.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 3, src: "./img/ph/3.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 4, src: "./img/ph/4.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 5, src: "./img/ph/5.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 6, src: "./img/ph/6.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 7, src: "./img/ph/7.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 8, src: "./img/ph/8.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 9, src: "./img/ph/9.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Canon AE-1", type: "Film Photography" },
    { id: 10, src: "./img/ph/10.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 11, src: "./img/ph/11.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 12, src: "./img/ph/12.jpg", location: "São Paulo, Brasil", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 13, src: "./img/ph/13.jpg", location: "Montevideo, Uruguay", year: "2018", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 14, src: "./img/ph/14.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 15, src: "./img/ph/15.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 16, src: "./img/ph/16.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 17, src: "./img/ph/17.jpg", location: "Camboriú, Brasil", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 18, src: "./img/ph/18.jpg", location: "São Paulo, Brasil", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 19, src: "./img/ph/19.jpg", location: "Camboriú, Brasil", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 20, src: "./img/ph/20.jpg", location: "El Pinar, Uruguay", year: "2016", camera: "LG Optimus 3D", type: "Digital Photography" },
    { id: 21, src: "./img/ph/21.jpg", location: "Camboriú, Brasil", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 22, src: "./img/ph/22.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 23, src: "./img/ph/23.jpg", location: "Camboriú, Brasil", year: "2017", camera: "Nikon D3100", type: "Digital Photography" },
    { id: 24, src: "./img/ph/24.jpg", location: "Montevideo, Uruguay", year: "2017", camera: "Nikon D3100", type: "Digital Photography" }
];
